# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from service.proto import component_snapshot_pb2 as service_dot_proto_dot_component__snapshot__pb2


class ComponentSnapshotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCameras = channel.unary_unary(
                '/roblox.girp.componentSnapshot.ComponentSnapshot/GetCameras',
                request_serializer=service_dot_proto_dot_component__snapshot__pb2.GetCamerasRequest.SerializeToString,
                response_deserializer=service_dot_proto_dot_component__snapshot__pb2.RccOutput.FromString,
                )


class ComponentSnapshotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComponentSnapshotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameras,
                    request_deserializer=service_dot_proto_dot_component__snapshot__pb2.GetCamerasRequest.FromString,
                    response_serializer=service_dot_proto_dot_component__snapshot__pb2.RccOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'roblox.girp.componentSnapshot.ComponentSnapshot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComponentSnapshot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/roblox.girp.componentSnapshot.ComponentSnapshot/GetCameras',
            service_dot_proto_dot_component__snapshot__pb2.GetCamerasRequest.SerializeToString,
            service_dot_proto_dot_component__snapshot__pb2.RccOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
